# set the baseURL for CI verification
baseURL = "/"
title = "Community Over Code Asia 2025"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true
#hasCJKLanguage = true
enableRobotsTXT = true

languageCode = "en-us"
DefaultContentLanguage = "en"



[params]
  author = "ALC-Beijing"
  description = "Welcome to Community Over Code (ApacheCon Asia) 2025"
  keywords = ["Community Over Code","Community Over Code Asia","ApacheCon Asia 2025", "Apache 软件基金会亚洲大会 2025"]
  schedule = ["2025-07-25", "2025-07-26", "2025-07-27"]

[languages.en]
languageName = "English"
weight = 1

[languages.zh]
languageName = "中文"
weight = 2

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

# menu for en (final list includes translated pages from /content)
[[languages.en.menu.main]]
name = "Schedule"
url = "/tracks.html"
weight = -100

[[languages.en.menu.main]]
name = "Guide"
url = "/guide/visa_letter_request.html"
weight = 4

[[languages.en.menu.main]]
name = "Venue + Travel"
url = "/venue_travel/venue.html"
weight = 5


# menu for ZH language (final list includes translated pages from /content)
[[languages.zh.menu.main]]
[[languages.zh.menu.main]]
name = "会议日程"
url = "/zh/tracks.html"
weight = -100


[[languages.zh.menu.main]]
name = "参会指南"
url = "/zh/guide/visa_letter_request.html"
weight = 4

[[languages.zh.menu.main]]
name = "会场 + 旅行"
url = "/zh/venue_travel/venue.html"
weight = 5
