# set the baseURL for CI verification
baseURL = "/"
title = "Community Over Code Asia 2026"
theme = "apachecon"
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = true
#hasCJKLanguage = true
enableRobotsTXT = true

languageCode = "en-us"
DefaultContentLanguage = "en"



[params]
  author = "ALC-Beijing"
  description = "Welcome to Community Over Code (ApacheCon Asia) 2026"
  keywords = ["Community Over Code","Community Over Code Asia","ApacheCon Asia 2026", "Apache 软件基金会亚洲大会 2026"]
  schedule = ["2026-08-07", "2026-08-08", "2026-08-09"]

[languages.en]
languageName = "English"
weight = 1

[languages.zh]
languageName = "中文"
weight = 2

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

# menu for en (final list includes translated pages from /content)
[[languages.en.menu.main]]
name = "Schedule"
url = "/tracks.html"
weight = -100

# menu for ZH language (final list includes translated pages from /content)
[[languages.zh.menu.main]]
[[languages.zh.menu.main]]
name = "会议日程"
url = "/zh/tracks.html"
weight = -100

